CREATE TABLE `User` (
  `ID` int(11) NOT NULL,
  `FIRST_NAME` varchar(50) DEFAULT NULL,
  `LAST_NAME` varchar(50) DEFAULT NULL,
  `BIRTHDAY` date DEFAULT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `SCORE` double DEFAULT NULL,
  `RANK` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;